name: strongR-frida

on:
  schedule:
    - cron: "0 9/12 * * *"
  workflow_dispatch:

jobs: 
  android_build:
    strategy:
      matrix:
        hash: 
          - 1f3c3c7c69a6fbfaaa35478261e5435e58e14c45
          - 34d7087fc9d16d32e76b2595978b51f5b2a0248c
          - b91e63b2e457557c85886b844511468ebac1f058
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - uses: fusion-engineering/setup-git-credentials@v2
      with:
        credentials: ${{secrets.GIT_CREDENTIALS}}

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup Android NDK
      id: setup-ndk
      uses: nttld/setup-ndk@v1.0.6
      with:
        ndk-version: r25b

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: install dependencies
      run: |
        sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install build-essential tree ninja-build gcc-multilib g++-multilib lib32stdc++-9-dev flex bison xz-utils ruby ruby-dev python3-requests python3-setuptools python3-dev python3-pip libc6-dev libc6-dev-i386 -y
        sudo gem install fpm -v 1.11.0 --no-document
        python3 -m pip install lief

    - name: build frida for Android
      shell: bash
      run: |
        git config --global user.name "${{ secrets.GIT_NAME }}"
        git config --global user.email "${{ secrets.GIT_EMAIL }}"
        git clone ${{ secrets.PATCH_REPO }}
        export ANDROID_NDK_ROOT=${{ steps.setup-ndk.outputs.ndk-path }}
        git clone --recurse-submodules https://github.com/frida/frida 
        git reset --hard ${{ matrix.hash }}
        cd frida/frida-core
        git am ../../Patchs/strongR-frida/frida-core/*.patch
    - name: two step patch   
      shell: bash
      run: |
        cd frida/frida-gum/gum
        git am ../../../Patchs/strongR-frida/frida-gum/*.patch
        cd ../../
        make core-android-arm64

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        path: ${{ github.workspace }}/frida/build/frida-android-arm64/bin/frida-server
